[package]
name = "calc"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.83"
prost = "0.13.3"
tokio = { version = "1.41.1", features = ["full"] }
tonic = "0.12.3"

[build-dependencies]
tonic-build = "0.12.3"
